# syntax=docker/dockerfile:1

FROM --platform=linux/amd64 golang:1.24.5-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/metad ./cmd/metad

FROM alpine:latest
WORKDIR /app

COPY --from=builder /out/metad /usr/local/bin/metad

EXPOSE 50051
EXPOSE 9090

ENTRYPOINT ["/usr/local/bin/metad"]
