services:
  metad:
    build:
      context: .
      dockerfile: Dockerfile.metad
    environment:
      DFS_REPLICATION_FACTOR: "3"
      DFS_METADATA_DB_PATH: /var/lib/dfs/metad.db
      DFS_JWT_SECRET: "supersecretkey"
    ports:
      - "50051:50051"
      - "9090:9090"
    volumes:
      - metad_db:/var/lib/dfs
      - ./certs/ca/ca.crt:/certs/ca.crt:ro
      - ./certs/metad/server.crt:/certs/server.crt:ro
      - ./certs/metad/server.key:/certs/server.key:ro
    networks:
      - dfs-net

  storaged1:
    build:
      context: .
      dockerfile: Dockerfile.storaged
    depends_on:
      - metad
    environment:
      DFS_STORAGE_DATA_PATH: /var/lib/dfs/storage
      DFS_STORAGE_CAPACITY_BYTES: "10737418240"
      DFS_STORAGE_NODE_ID: storage-1
      DFS_STORAGE_LISTEN_ADDR: storaged1:50052
      DFS_METADATA_ADDR: metad:50051
    ports:
      - "50052:50052"
      - "9101:9091"
    volumes:
      - storaged1_data:/var/lib/dfs/storage
      - ./certs/ca/ca.crt:/certs/ca.crt:ro
      - ./certs/storaged1/server.crt:/certs/server.crt:ro
      - ./certs/storaged1/server.key:/certs/server.key:ro
    networks:
      - dfs-net

  storaged2:
    build:
      context: .
      dockerfile: Dockerfile.storaged
    depends_on:
      - metad
    environment:
      DFS_STORAGE_DATA_PATH: /var/lib/dfs/storage
      DFS_STORAGE_CAPACITY_BYTES: "10737418240"
      DFS_STORAGE_NODE_ID: storage-2
      DFS_STORAGE_LISTEN_ADDR: storaged2:50052
      DFS_METADATA_ADDR: metad:50051
    ports:
      - "50053:50052"
      - "9102:9091"
    volumes:
      - storaged2_data:/var/lib/dfs/storage
      - ./certs/ca/ca.crt:/certs/ca.crt:ro
      - ./certs/storaged2/server.crt:/certs/server.crt:ro
      - ./certs/storaged2/server.key:/certs/server.key:ro
    networks:
      - dfs-net

  storaged3:
    build:
      context: .
      dockerfile: Dockerfile.storaged
    depends_on:
      - metad
    environment:
      DFS_STORAGE_DATA_PATH: /var/lib/dfs/storage
      DFS_STORAGE_CAPACITY_BYTES: "10737418240"
      DFS_STORAGE_NODE_ID: storage-3
      DFS_STORAGE_LISTEN_ADDR: storaged3:50052
      DFS_METADATA_ADDR: metad:50051
    ports:
      - "50054:50052"
      - "9103:9091"
    volumes:
      - storaged3_data:/var/lib/dfs/storage
      - ./certs/ca/ca.crt:/certs/ca.crt:ro
      - ./certs/storaged3/server.crt:/certs/server.crt:ro
      - ./certs/storaged3/server.key:/certs/server.key:ro
    networks:
      - dfs-net

  prometheus:
    image: prom/prometheus:latest
    container_name: dfs-prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dfs-net
    depends_on:
      - metad
      - storaged1
      - storaged2
      - storaged3

networks:
  dfs-net:
    driver: bridge

volumes:
  metad_db:
  storaged1_data:
  storaged2_data:
  storaged3_data:
