# syntax=docker/dockerfile:1

FROM --platform=linux/amd64 golang:1.24.5-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/storaged ./cmd/storaged

FROM alpine:latest
WORKDIR /app

COPY --from=builder /out/storaged /usr/local/bin/storaged

EXPOSE 50052
EXPOSE 9091

ENTRYPOINT ["/usr/local/bin/storaged"]
