global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "metad"
    static_configs:
      - targets: ["metad:9090"]

  - job_name: "storaged"
    static_configs:
      - targets:
          - "storaged1:9091"
          - "storaged2:9091"
          - "storaged3:9091"