// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: internal/protocol/node/node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port
	CapacityBytes  int64                  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,4,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_protocol_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatRequest) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_protocol_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_node_proto_rawDescGZIP(), []int{1}
}

type CopyChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyChunkRequest) Reset() {
	*x = CopyChunkRequest{}
	mi := &file_internal_protocol_node_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyChunkRequest) ProtoMessage() {}

func (x *CopyChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyChunkRequest.ProtoReflect.Descriptor instead.
func (*CopyChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_node_proto_rawDescGZIP(), []int{2}
}

func (x *CopyChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *CopyChunkRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

type CopyChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyChunkResponse) Reset() {
	*x = CopyChunkResponse{}
	mi := &file_internal_protocol_node_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyChunkResponse) ProtoMessage() {}

func (x *CopyChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyChunkResponse.ProtoReflect.Descriptor instead.
func (*CopyChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_node_proto_rawDescGZIP(), []int{3}
}

func (x *CopyChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_protocol_node_node_proto protoreflect.FileDescriptor

const file_internal_protocol_node_node_proto_rawDesc = "" +
	"\n" +
	"!internal/protocol/node/node.proto\x12\x04node\"\x95\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\x12'\n" +
	"\x0favailable_bytes\x18\x04 \x01(\x03R\x0eavailableBytes\"\x13\n" +
	"\x11HeartbeatResponse\"T\n" +
	"\x10CopyChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"-\n" +
	"\x11CopyChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x89\x01\n" +
	"\vNodeService\x12<\n" +
	"\tHeartbeat\x12\x16.node.HeartbeatRequest\x1a\x17.node.HeartbeatResponse\x12<\n" +
	"\tCopyChunk\x12\x16.node.CopyChunkRequest\x1a\x17.node.CopyChunkResponseB=Z;github.com/rohanyadav1024/dfs/internal/protocol/node;nodepbb\x06proto3"

var (
	file_internal_protocol_node_node_proto_rawDescOnce sync.Once
	file_internal_protocol_node_node_proto_rawDescData []byte
)

func file_internal_protocol_node_node_proto_rawDescGZIP() []byte {
	file_internal_protocol_node_node_proto_rawDescOnce.Do(func() {
		file_internal_protocol_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_node_node_proto_rawDesc), len(file_internal_protocol_node_node_proto_rawDesc)))
	})
	return file_internal_protocol_node_node_proto_rawDescData
}

var file_internal_protocol_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_protocol_node_node_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: node.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: node.HeartbeatResponse
	(*CopyChunkRequest)(nil),  // 2: node.CopyChunkRequest
	(*CopyChunkResponse)(nil), // 3: node.CopyChunkResponse
}
var file_internal_protocol_node_node_proto_depIdxs = []int32{
	0, // 0: node.NodeService.Heartbeat:input_type -> node.HeartbeatRequest
	2, // 1: node.NodeService.CopyChunk:input_type -> node.CopyChunkRequest
	1, // 2: node.NodeService.Heartbeat:output_type -> node.HeartbeatResponse
	3, // 3: node.NodeService.CopyChunk:output_type -> node.CopyChunkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_node_node_proto_init() }
func file_internal_protocol_node_node_proto_init() {
	if File_internal_protocol_node_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_node_node_proto_rawDesc), len(file_internal_protocol_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_node_node_proto_goTypes,
		DependencyIndexes: file_internal_protocol_node_node_proto_depIdxs,
		MessageInfos:      file_internal_protocol_node_node_proto_msgTypes,
	}.Build()
	File_internal_protocol_node_node_proto = out.File
	file_internal_protocol_node_node_proto_goTypes = nil
	file_internal_protocol_node_node_proto_depIdxs = nil
}
