// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: internal/protocol/storage/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *PutChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{1}
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{5}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_internal_protocol_storage_storage_proto protoreflect.FileDescriptor

const file_internal_protocol_storage_storage_proto_rawDesc = "" +
	"\n" +
	"'internal/protocol/storage/storage.proto\x12\astorage\"@\n" +
	"\x0fPutChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x12\n" +
	"\x10PutChunkResponse\",\n" +
	"\x0fGetChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x15\n" +
	"\x13DeleteChunkResponse\"\x0f\n" +
	"\rHealthRequest\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy2\x97\x02\n" +
	"\x0eStorageService\x12?\n" +
	"\bPutChunk\x12\x18.storage.PutChunkRequest\x1a\x19.storage.PutChunkResponse\x12?\n" +
	"\bGetChunk\x12\x18.storage.GetChunkRequest\x1a\x19.storage.GetChunkResponse\x12H\n" +
	"\vDeleteChunk\x12\x1b.storage.DeleteChunkRequest\x1a\x1c.storage.DeleteChunkResponse\x129\n" +
	"\x06Health\x12\x16.storage.HealthRequest\x1a\x17.storage.HealthResponseBCZAgithub.com/rohanyadav1024/dfs/internal/protocol/storage;storagepbb\x06proto3"

var (
	file_internal_protocol_storage_storage_proto_rawDescOnce sync.Once
	file_internal_protocol_storage_storage_proto_rawDescData []byte
)

func file_internal_protocol_storage_storage_proto_rawDescGZIP() []byte {
	file_internal_protocol_storage_storage_proto_rawDescOnce.Do(func() {
		file_internal_protocol_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_storage_storage_proto_rawDesc), len(file_internal_protocol_storage_storage_proto_rawDesc)))
	})
	return file_internal_protocol_storage_storage_proto_rawDescData
}

var file_internal_protocol_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protocol_storage_storage_proto_goTypes = []any{
	(*PutChunkRequest)(nil),     // 0: storage.PutChunkRequest
	(*PutChunkResponse)(nil),    // 1: storage.PutChunkResponse
	(*GetChunkRequest)(nil),     // 2: storage.GetChunkRequest
	(*GetChunkResponse)(nil),    // 3: storage.GetChunkResponse
	(*DeleteChunkRequest)(nil),  // 4: storage.DeleteChunkRequest
	(*DeleteChunkResponse)(nil), // 5: storage.DeleteChunkResponse
	(*HealthRequest)(nil),       // 6: storage.HealthRequest
	(*HealthResponse)(nil),      // 7: storage.HealthResponse
}
var file_internal_protocol_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageService.PutChunk:input_type -> storage.PutChunkRequest
	2, // 1: storage.StorageService.GetChunk:input_type -> storage.GetChunkRequest
	4, // 2: storage.StorageService.DeleteChunk:input_type -> storage.DeleteChunkRequest
	6, // 3: storage.StorageService.Health:input_type -> storage.HealthRequest
	1, // 4: storage.StorageService.PutChunk:output_type -> storage.PutChunkResponse
	3, // 5: storage.StorageService.GetChunk:output_type -> storage.GetChunkResponse
	5, // 6: storage.StorageService.DeleteChunk:output_type -> storage.DeleteChunkResponse
	7, // 7: storage.StorageService.Health:output_type -> storage.HealthResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_storage_storage_proto_init() }
func file_internal_protocol_storage_storage_proto_init() {
	if File_internal_protocol_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_storage_storage_proto_rawDesc), len(file_internal_protocol_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_storage_storage_proto_goTypes,
		DependencyIndexes: file_internal_protocol_storage_storage_proto_depIdxs,
		MessageInfos:      file_internal_protocol_storage_storage_proto_msgTypes,
	}.Build()
	File_internal_protocol_storage_storage_proto = out.File
	file_internal_protocol_storage_storage_proto_goTypes = nil
	file_internal_protocol_storage_storage_proto_depIdxs = nil
}
