// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: internal/protocol/metadata/metadata.proto

package metadatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,2,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareUploadRequest) Reset() {
	*x = PrepareUploadRequest{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareUploadRequest) ProtoMessage() {}

func (x *PrepareUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareUploadRequest.ProtoReflect.Descriptor instead.
func (*PrepareUploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PrepareUploadRequest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

type PrepareUploadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadSessionId string                 `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Chunks          []*ChunkPlan           `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrepareUploadResponse) Reset() {
	*x = PrepareUploadResponse{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareUploadResponse) ProtoMessage() {}

func (x *PrepareUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareUploadResponse.ProtoReflect.Descriptor instead.
func (*PrepareUploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareUploadResponse) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

func (x *PrepareUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *PrepareUploadResponse) GetChunks() []*ChunkPlan {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type CommitUploadRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionId     string                  `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReplicaMap    map[string]*ReplicaList `protobuf:"bytes,2,rep,name=replica_map,json=replicaMap,proto3" json:"replica_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadRequest) Reset() {
	*x = CommitUploadRequest{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest) ProtoMessage() {}

func (x *CommitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadRequest.ProtoReflect.Descriptor instead.
func (*CommitUploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *CommitUploadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommitUploadRequest) GetReplicaMap() map[string]*ReplicaList {
	if x != nil {
		return x.ReplicaMap
	}
	return nil
}

type ReplicaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaList) Reset() {
	*x = ReplicaList{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaList) ProtoMessage() {}

func (x *ReplicaList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaList.ProtoReflect.Descriptor instead.
func (*ReplicaList) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaList) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type CommitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse) Reset() {
	*x = CommitUploadResponse{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse) ProtoMessage() {}

func (x *CommitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadResponse.ProtoReflect.Descriptor instead.
func (*CommitUploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,3,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	Chunks        []*ChunkPlan           `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileResponse) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *GetFileResponse) GetChunks() []*ChunkPlan {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{8}
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{9}
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileSummary         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFiles() []*FileSummary {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,3,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSummary) Reset() {
	*x = FileSummary{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSummary) ProtoMessage() {}

func (x *FileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSummary.ProtoReflect.Descriptor instead.
func (*FileSummary) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *FileSummary) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileSummary) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileSummary) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

type ChunkPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	OffsetBytes   int64                  `protobuf:"varint,2,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Replicas      []*Replica             `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPlan) Reset() {
	*x = ChunkPlan{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPlan) ProtoMessage() {}

func (x *ChunkPlan) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPlan.ProtoReflect.Descriptor instead.
func (*ChunkPlan) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *ChunkPlan) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkPlan) GetOffsetBytes() int64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *ChunkPlan) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ChunkPlan) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_metadata_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_internal_protocol_metadata_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *Replica) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Replica) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_internal_protocol_metadata_metadata_proto protoreflect.FileDescriptor

const file_internal_protocol_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	")internal/protocol/metadata/metadata.proto\x12\bmetadata\"[\n" +
	"\x14PrepareUploadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x02 \x01(\x03R\rfileSizeBytes\"\x89\x01\n" +
	"\x15PrepareUploadResponse\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12+\n" +
	"\x06chunks\x18\x03 \x03(\v2\x13.metadata.ChunkPlanR\x06chunks\"\xda\x01\n" +
	"\x13CommitUploadRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12N\n" +
	"\vreplica_map\x18\x02 \x03(\v2-.metadata.CommitUploadRequest.ReplicaMapEntryR\n" +
	"replicaMap\x1aT\n" +
	"\x0fReplicaMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.metadata.ReplicaListR\x05value:\x028\x01\"(\n" +
	"\vReplicaList\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"\x16\n" +
	"\x14CommitUploadResponse\")\n" +
	"\x0eGetFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x9c\x01\n" +
	"\x0fGetFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x03 \x01(\x03R\rfileSizeBytes\x12+\n" +
	"\x06chunks\x18\x04 \x03(\v2\x13.metadata.ChunkPlanR\x06chunks\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x14\n" +
	"\x12DeleteFileResponse\"\x12\n" +
	"\x10ListFilesRequest\"@\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.metadata.FileSummaryR\x05files\"k\n" +
	"\vFileSummary\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x03 \x01(\x03R\rfileSizeBytes\"\x97\x01\n" +
	"\tChunkPlan\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12!\n" +
	"\foffset_bytes\x18\x02 \x01(\x03R\voffsetBytes\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12-\n" +
	"\breplicas\x18\x04 \x03(\v2\x11.metadata.ReplicaR\breplicas\"<\n" +
	"\aReplica\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\x81\x03\n" +
	"\x0fMetadataService\x12P\n" +
	"\rPrepareUpload\x12\x1e.metadata.PrepareUploadRequest\x1a\x1f.metadata.PrepareUploadResponse\x12M\n" +
	"\fCommitUpload\x12\x1d.metadata.CommitUploadRequest\x1a\x1e.metadata.CommitUploadResponse\x12>\n" +
	"\aGetFile\x12\x18.metadata.GetFileRequest\x1a\x19.metadata.GetFileResponse\x12G\n" +
	"\n" +
	"DeleteFile\x12\x1b.metadata.DeleteFileRequest\x1a\x1c.metadata.DeleteFileResponse\x12D\n" +
	"\tListFiles\x12\x1a.metadata.ListFilesRequest\x1a\x1b.metadata.ListFilesResponseBEZCgithub.com/rohanyadav1024/dfs/internal/protocol/metadata;metadatapbb\x06proto3"

var (
	file_internal_protocol_metadata_metadata_proto_rawDescOnce sync.Once
	file_internal_protocol_metadata_metadata_proto_rawDescData []byte
)

func file_internal_protocol_metadata_metadata_proto_rawDescGZIP() []byte {
	file_internal_protocol_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_internal_protocol_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_metadata_metadata_proto_rawDesc), len(file_internal_protocol_metadata_metadata_proto_rawDesc)))
	})
	return file_internal_protocol_metadata_metadata_proto_rawDescData
}

var file_internal_protocol_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_protocol_metadata_metadata_proto_goTypes = []any{
	(*PrepareUploadRequest)(nil),  // 0: metadata.PrepareUploadRequest
	(*PrepareUploadResponse)(nil), // 1: metadata.PrepareUploadResponse
	(*CommitUploadRequest)(nil),   // 2: metadata.CommitUploadRequest
	(*ReplicaList)(nil),           // 3: metadata.ReplicaList
	(*CommitUploadResponse)(nil),  // 4: metadata.CommitUploadResponse
	(*GetFileRequest)(nil),        // 5: metadata.GetFileRequest
	(*GetFileResponse)(nil),       // 6: metadata.GetFileResponse
	(*DeleteFileRequest)(nil),     // 7: metadata.DeleteFileRequest
	(*DeleteFileResponse)(nil),    // 8: metadata.DeleteFileResponse
	(*ListFilesRequest)(nil),      // 9: metadata.ListFilesRequest
	(*ListFilesResponse)(nil),     // 10: metadata.ListFilesResponse
	(*FileSummary)(nil),           // 11: metadata.FileSummary
	(*ChunkPlan)(nil),             // 12: metadata.ChunkPlan
	(*Replica)(nil),               // 13: metadata.Replica
	nil,                           // 14: metadata.CommitUploadRequest.ReplicaMapEntry
}
var file_internal_protocol_metadata_metadata_proto_depIdxs = []int32{
	12, // 0: metadata.PrepareUploadResponse.chunks:type_name -> metadata.ChunkPlan
	14, // 1: metadata.CommitUploadRequest.replica_map:type_name -> metadata.CommitUploadRequest.ReplicaMapEntry
	12, // 2: metadata.GetFileResponse.chunks:type_name -> metadata.ChunkPlan
	11, // 3: metadata.ListFilesResponse.files:type_name -> metadata.FileSummary
	13, // 4: metadata.ChunkPlan.replicas:type_name -> metadata.Replica
	3,  // 5: metadata.CommitUploadRequest.ReplicaMapEntry.value:type_name -> metadata.ReplicaList
	0,  // 6: metadata.MetadataService.PrepareUpload:input_type -> metadata.PrepareUploadRequest
	2,  // 7: metadata.MetadataService.CommitUpload:input_type -> metadata.CommitUploadRequest
	5,  // 8: metadata.MetadataService.GetFile:input_type -> metadata.GetFileRequest
	7,  // 9: metadata.MetadataService.DeleteFile:input_type -> metadata.DeleteFileRequest
	9,  // 10: metadata.MetadataService.ListFiles:input_type -> metadata.ListFilesRequest
	1,  // 11: metadata.MetadataService.PrepareUpload:output_type -> metadata.PrepareUploadResponse
	4,  // 12: metadata.MetadataService.CommitUpload:output_type -> metadata.CommitUploadResponse
	6,  // 13: metadata.MetadataService.GetFile:output_type -> metadata.GetFileResponse
	8,  // 14: metadata.MetadataService.DeleteFile:output_type -> metadata.DeleteFileResponse
	10, // 15: metadata.MetadataService.ListFiles:output_type -> metadata.ListFilesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_protocol_metadata_metadata_proto_init() }
func file_internal_protocol_metadata_metadata_proto_init() {
	if File_internal_protocol_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_metadata_metadata_proto_rawDesc), len(file_internal_protocol_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_internal_protocol_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_internal_protocol_metadata_metadata_proto_msgTypes,
	}.Build()
	File_internal_protocol_metadata_metadata_proto = out.File
	file_internal_protocol_metadata_metadata_proto_goTypes = nil
	file_internal_protocol_metadata_metadata_proto_depIdxs = nil
}
